node {
    try {
        def String registry_url
        withEnv(['registryCredential=private-registry', 'image=""', 'BRANCH=""']) {
            stage('Checkout') {}
            stage('Read deployment configurations') {}
            stage('Build and Test') {

            }
            stage('Push to Registry') {}
        }
    } catch(e) {
        currentBuild.result = "FAILED"
        throw e
    } finally {

    }
}