replicaCount: 1
image:
  repository: 10.124.69.3:30444/hoangnv46_test/book-api
  pullpolicy: IfNotPresent
  tag: "stg-8c1af0e"
service:
  type: NodePort
  port: 3000
extraEnvVars:
  - name: DB_NAME
    value: mongodb
  - name: DB_HOST
    value: mongodb
  - name: DB_PORT
    value: "27017"
