apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "order.labels" . | indent 4 }}
spec:
  selector: {{ include "order.selectorLabels" . | indent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
    name: http
