kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: bookapp-api
  namespace: hoangnv46-namespace
  # annotations:
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  #   nginx.ingress.kubernetes.io/limit-rps: "30"
  #   nginx.ingress.kubernetes.io/limit-burst-multiplier: "9"
  #   nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
  #   nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  #   nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: bookapp.vinbase.com
      http:
        paths:
          - path: /book
            pathType: Prefix
            backend:
              service:
                name: book-api
                port:
                  number: 3000
          - path: /customer-api
            pathType: Prefix
            backend:
              service:
                name: customer-api
                port:
                  number: 4000
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order-api
                port:
                  number: 5000