apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "order.selectorLabels" . | indent 4 }}
spec:
  revisionHistoryLimit: 2
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels: {{ include "order.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels: {{ include "order.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http 
              containerPort: 5000
              protocol: TCP
          env: 
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
 