apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service
  labels:
    component: books-service
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy: # change here
    type: RollingUpdate
  selector:
    matchLabels:
      component: books-service
  template:
    metadata:
      labels:
        component: books-service
    spec:
      containers:
        - name: books-service
          image: 14802000/books:latest
          envFrom:
            - configMapRef:
                name: microservice-cm