apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-healthcheck
  namespace: argocd
  labels:
    component: argocd-cm-healthcheck
data:
  resource.customizations: |
    extensions/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs