apiVersion: v1
kind: Service
metadata:
  name: books
  labels: 
    component: books
spec:
  selector: # service su dung de biet pod nao minh can quan ly
    component: books-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
