apiVersion: v2
name: order-api
description: A Helm chart for order-api

type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.12.0

