replicaCount: 1
image:
  repository: 10.124.69.3:30444/hoangnv46_test/order-api
  pullpolicy: IfNotPresent
  tag: "stg-0c146b1"
service:
  type: ClusterIP
  port: 5000
extraEnvVars:
  - name: DB_NAME
    value: mongodb
  - name: DB_HOST
    value: mongodb
  - name: DB_PORT
    value: "27017"
